[package]
name = "girl_technology"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7", features = ["macros"] }
diesel = { version = "2.1", features = ["postgres"] }
dotenvy = "0.15"
clap = { version = "4", features = ["derive"] }
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
tera = "1.19"
tokio = { version = "1", features = ["full"] }

[features]
# Whether to build with admin routes
admin = []
