[package]
name = "girl_technology"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/p0lyw0lf/girl.technology"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7", features = ["macros"] }
diesel = { version = "2.1", features = ["postgres"] }
dotenvy = "0.15"
clap = { version = "4", features = ["derive"] }
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
tera = "1.19"
tokio = { version = "1", features = ["full"] }

[features]
# Whether to build with admin routes
admin = []

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.9.0"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-unknown-linux-gnu"]
# Publish jobs to run in CI
pr-run-mode = "plan"
